server:
  port: 0
  
spring:
  application:
    name: DEPT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    config:
      import-check: 
        enabled: false
        import: 
          configserver: http://localhost:9626